### ISSUE TITLE
Reuse of UK standars on public services

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/CPSV-AP#10]
I don't know if you are aware of https://standards.esd.org.uk/?
I've just found it and I think that we can reuse some of these lists of values

**Comment by barthelemyf** [comment]
Thank you for your input. The work of the ESD has been considered recently as part of the work on the taxonomy of public services. This will be discussed further during the webinar of 6th February. Nevertheless, we propose to close this issue for now.
