### ISSUE TITLE
ConctactPoint: HasEmail and HasTelephone 

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#101]
Following Core Public Organisation Vocabulary, the 2 URI properties should be :

http://data.europa.eu/m8g/email
http://data.europa.eu/m8g/telephone

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to:
- Change the URI of the "has email" property from http://data.europa.eu/m8g/hasEmail to http://data.europa.eu/m8g/email.
- Change the URI if the "has telephone" property from http://data.europa.eu/m8g/hasTelephone to http://data.europa.eu/m8g/telephone.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
