### ISSUE TITLE
UML editorial: dcat:Dataset - landing page - cardinality

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#104]
In the diagram, the cardinality is expressed as 0..n while it should be 0..*

Same for Evidence.relatedDocumentation

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to:
- Change landingPage cardinality from 0..n to 0..*.
- Change relatedDocumentation cardinality from 0..n to 0..*.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
