### ISSUE TITLE
UML-diagram: cv::Address should be locn::Address

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#105]
In the [UML-diagram](https://semiceu.github.io/CPSV-AP/releases/3.0.0/html/overview.jpg), the URI for the class Address is now cv::Address, while [locn::Address](https://www.w3.org/ns/locn#Address) is used in the text which I believe is the correct one.

**Comment by EmidioStani** [comment]
Thanks for pointing out this issues, it will be fixed in the next release.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to change cv::Address to locn::Address.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
