### ISSUE TITLE
ContactPoint - openingHours should be 0..*

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#106]
The property openingHours (cv::openingHours) in the class Contact Point (cv::ContactPoint) has now Literal as the Expected Range. 

It should be Text (rdf:langString), because this is a free text property, so it will be language-dependent. 

We noticed also the Usage note saying "Days are specified using two-letter combinations: Mo, Tu, We, Th, Fr, Sa, Su." which are the two-letter combinations for the English names of the days. The two-letter combinations in other languages may and will be different. So the Usage note should be modified, e.g. "In English, days are ...".

**Comment by EmidioStani** [comment]
The proposition (that will be discussed during in Core Vocabularies webinar of 27/10) is to move the property in the class TemporalEntity as a "description" with a Text (langString),  with cardinality (0..*).

The usage note will be then updated.

**Comment by EmidioStani** [comment]
The solution will follow the issue #109
