### ISSUE TITLE
Expected range for dct:spatial in the class Public Organization

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#108]
The expected range for the property spatial (`dct:spatial`) in the class [Public Organization](https://semiceu.github.io/CPSV-AP/releases/3.0.0/#Public%20Organization), is now pointing to a controlled vocabulary (http://data.europa.eu/88u/dataset/atu-type). 

Shouldn't it be `dct:Location` (same as the one for `dct:spatial` in the class [Public Service](https://semiceu.github.io/CPSV-AP/releases/3.0.0/#Public%20Service))?

**Comment by EmidioStani** [comment]
During the webinar on 27 October, there will be a talk about the issue: https://github.com/SEMICeu/CPOV/issues/22 where the proposal is to change it to Location recommending using the URI of http://data.europa.eu/88u/dataset/atu-type

I close this issue as it belongs to CPOV and discussion will continue there
