### ISSUE TITLE
spatial - use of the Administrative Territorial Units by local public authorities

### ISSUE THREAD

**Issue by barthelemyf** [SEMICeu/CPSV-AP#11]
As raised by [anarosa-es](https://github.com/anarosa-es) in [Range of dct:spatial is skos:Concept](https://github.com/catalogue-of-services-isa/CPSV-AP/issues/3): 

> While national and regional units are likely to maintain their quantity and names, this is not the case of local public authorities (at least in my country). Therefore, keeping ATU up-to-date with thousands of local units seems unrealistic.

As proposed by [anarosa-es](https://github.com/anarosa-es), one solution could be to have: 

> one property with the public service's territorial range only in terms of "national/regional/province/local/other" ("other" for rare cases) could be useful. This property combined with the public service's competent authority (a public organization has its address), could be enough to define the spatial scope of the public service and to avoid the use of ATU.

What is the position of the Working Group members regarding this?

**Comment by barthelemyf** [comment]
During the webinar of last April 2018, the following discussion took place: 
Changing the range to dct:Location without adding a territorial range property would allow users to identify whether a service is local, regional, etc. A national service could have applicability on the local level, e.g. getting married is a national/federal service administered on the local level, which may also have some local aspects. A property like territorial range will always be debateable, so it’s better to allow this to be derived from the “spatial” property. Those that feel that a property for “territorial range” as described above is still necessary, can add this at the national level if needed – CPSV-AP is meant to be personalised.
[anarosa-es](https://github.com/anarosa-es) pointed out that there may be some confusion between the competent authority and the public service territorial scope. Additionally, for public services with a range covering many local authorities, all of these local authorities might have to be mentioned. However, since this is an optional property, this is not a real problem.

**Comment by Maxservais** [comment]
As agreed during the CPSV-AP webinar of 10/04/2019, the task group will investigate the possibility to use NUTS code for geographical locations of Public services or, as suggested by Bart Hanssens, to use Geonames as it is done in DCAT-AP.

**Comment by Maxservais** [comment]
**Findings**: There is no currently maintained list of NUTS codes expressed as RDF. Currently, DCAT-AP suggests to use MDR Authorities List (continents, countries, etc.) and geonames. The former are expressed as skos:Concept while the latter are expressed as gn:Feature which is a subclass of http://schema.org/Place and http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing.

**Next steps**: Members of the working group are invited to share a list of maintained NUTS codes expressed as RDF on GitHub.

**Comment by kareljanr** [comment]
A maintained list of the NUTS codes can be found here:
[](http://nuts.geovocab.org/id/index.html)

**Comment by guascce** [comment]
Following this[ link ](https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/nuts) you will find an rdf file to represent the list of NUTS codes. Can you check whether it supports your needs?

**Comment by NathanGhesq** [comment]
We acknowledge that the existence of the NUTS code from the Publication Office could be used as a property of the Location class. In addition, Core Vocabularies include an [Administrative Unit class](https://semiceu.github.io/Core-Location-Vocabulary/releases/2.00/#Administrative%20Unit) with code levels that would allow a hierarchical structure.

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, recommended controlled vocabularies for the spatial property are recommended in the usage notes.
