### ISSUE TITLE
Better to have the inverse of cv:playsRole?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#110]
Currently, the class `foaf:Agent` has a property `cv:playsRole` with range `cv:Participation`. 

Wouldn't it be "more natural" to have the property the other way: `cv:Participation` `cv:rolePlayedBy` `foaf:Agent`? 

This may also make it easier to implement, in the way that you don't need to scan all the instances of foaf:Agent in order to know who plays role in which participation.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to:
- Restrict participates 1..* and hasParticipant 1..1.
- Use "participates" instead of "playsRole".

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
