### ISSUE TITLE
What is meant to be covered by cpsv:PublicService in CPSV-AP?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#112]
1. Is a "Public Registry Service" defined in [BRegDCAT-AP](https://github.com/SEMICeu/BregDCAT-AP) within the scope of CPSV-AP? [In BRegDCAT-AP, there is a class called "Public Registry Service", which also uses the URI `cpsv:PublicService`, and which has the following usage note: "A Registry Service is a public service that creates, maintains and/or manages Base Registries or a Registry of Base Registries. This service, provided by public administrations, or by other organisations on their behalf, stores and provides basic information on authoritative data items such as people, companies, vehicles, licences, buildings, locations and roads."]
2. Is an (e-) identification, authentication & authorization service provided by or on behalf of a public organisation within the sope of CPSV-AP?

**Comment by EmidioStani** [comment]
I think the first question should be dealt in BregDCAT-AP working group, by reading the above usage note I would create a subclass of PublicService as it would have more context. 

For the second question, yes I think in CPSV-AP a Public Service could cover these 3 services  which I would group under a "digital public service"

**Comment by EmidioStani** [comment]
The issue, in relation to CPSV-AP has been dealt, it can continue on BregDCAT-AP
