### ISSUE TITLE
[CPSV-APv.3.1] Agent - participates: why mandatory (1..*)?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#113]
In v.3.1 of CPSV-AP, the cardinality for the property "participates" (cv:participates) in [the class Agent](https://semiceu.github.io/CPSV-AP/releases/3.1.0/#Agent) is now 1..*.  

Why is it mandatory (1..*)?

**Comment by EmidioStani** [comment]
Hello @jimjyang,

this is related to issue https://github.com/SEMICeu/CPSV-AP/issues/110

**Comment by jimjyang** [comment]
@EmidioStani 

I know it was discussed at the webinar, however ...

Example 1: A Public service must have at least one Public organisation as its Competent authority. With this property "participates" mandatory, you have to create a Participation for your Competent authorities (that don't play other roles in the service), with the role "Competent authority" (or suchlike). We think this is unnecessary duplicate of information. 

Example 2:  With this property "participates" mandatory, you have to create a Participation for all the Organisations that own a Channel (and that don't play other roles in the service), with the role "channel owner" (or suchlike). Similarly, you must create a Participation for all the organisations that define a Cost, etc. Again, we think this is unnecessary duplicate of information.

Unnecessary duplication complicates the implementation.

**Comment by EmidioStani** [comment]
For the release of CPSV-AP v3.1 the cardinality the min cardinality will be relaxed

**Comment by EmidioStani** [comment]
This issue can be closed as for release [3.1.1](https://semiceu.github.io/CPSV-AP/releases/3.1.1/)
