### ISSUE TITLE
[CPSV-AP v.3.1] in the class Public Service: why creating a new URI cv:releatedService instead of using the existing dct:releated?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#114]
For the property ["related service"](https://semiceu.github.io/CPSV-AP/releases/3.1.0/#Public%20Service%3Arelated%20service) in the class Public Service in CPSV-AP v.3.1, why not use `dct:relation` (as in CPSV-AP v.3.0) instead of creating a new/own URI `cv:relatedService`? 

[Similarly, for the property "requires" in the same class, you use the existing dct:requires instead of creating a new/own URI cv:requiresService]

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

this is because of issue #63

the 2 new URI are subproperty of dct:relation see: https://github.com/SEMICeu/CPSV-AP/blob/master/releases/3.1.0/rdf/cpsv-ap.ttl#L213
