### ISSUE TITLE
processingTime:Duration - data type error in PDF of model

### ISSUE THREAD

**Issue by Maxservais** [SEMICeu/CPSV-AP#13]
In the [PNG of the model](https://joinup.ec.europa.eu/rdf_entity/http_e_f_fdata_ceuropa_ceu_fw21_ff0d9a860_be555_b4fbe_b8b53_b11df532d15e8), "processingTime" has datatype "Duration". However, in the [PDF of the Specification](https://joinup.ec.europa.eu/rdf_entity/http_e_f_fdata_ceuropa_ceu_fw21_f08950374_b7f7c_b4b5a_b94c1_b40d72ffad670), "processingTime" is indicated as text ( rdfs:Literal). The PNG should be fixed.

**Comment by EmidioStani** [comment]
Actually processingTime has datatype Duration if you see in schema.org, and Duration values are strings in the form of ISO8601 standard, I think the PDF should be fixed to be precise as the PNG
