### ISSUE TITLE
Definition of Participation class is unclear

### ISSUE THREAD

**Issue by Maxservais** [SEMICeu/CPSV-AP#22]
A clarification regarding the Participation class definition was made on the 27/10/2016 [here](https://joinup.ec.europa.eu/discussion/clarification-participation-class). 
However, it seems to be still unclear. A possible solution would be to add a mapping towards the org:Membership class. To be discussed.

**Comment by Maxservais** [comment]
During the CPSV-AP Webinar of the 10th of April, it has been agreed that the task group would look into the definition of the membership class to check whether it is semantically equivalent to the Participation class.

**Comment by EmidioStani** [comment]
Hints: https://joinup.ec.europa.eu/solution/core-public-service-vocabulary-application-profile/discussion/addition-more-detail-role-agent (see Phil Archer's comment on Thu, 19/05/2016 - 12:49
