### ISSUE TITLE
Change range of dct:spatial for Class Public Organization

### ISSUE THREAD

**Issue by Maxservais** [SEMICeu/CPSV-AP#23]
For the class "Public Organization", the range of dct:spatial is indicated as skos:Concept. However, in the Dublin Core specs, dct:spatial has range dct:Location and not skos:Concept.

**Comment by Maxservais** [comment]
During the webinar of the 10th of April 2019, It was agreed that the range of dct:spatial would be changed from skos:Concept to dct:Location.

**Comment by Maxservais** [comment]
The issue will be left open for the next two weeks for review by the community and the working group members. After the period of two weeks, the issue will be closed.

**Comment by GabrieleCiasullo** [comment]
I agree with the change of the range for the property dct:spatial from skos:Concept to dct:Location, both to be compliant to DC specs and even to align it to the DCAT-AP specs that use the same property with the same range.
