### ISSUE TITLE
Range of dct:spatial is skos:Concept

### ISSUE THREAD

**Issue by ioanano** [SEMICeu/CPSV-AP#3]
Issue raised by Makx Dekkers: 
The fact that the range of dct:spatial in CPSV-AP is declared to be skos:Concept is an error – DCMI defines the range as dct:Location. That the object of the property (e.g. a term in the MDR NAL) is defined as a skos:Concept is irrelevant – usage as the object of the property triggers the inference that it is (also) a dct:Location. The current definition in CPSV-AP breaks that inference.

**Comment by ioanano** [comment]
Proposal: change skos:concept to dct:Location.

**Comment by anarosa-es** [comment]
While national and regional units are likely to maintain their quantity and names, this is not the case of local public authorities (at least in my country). Therefore, keeping ATU up-to-date with thousands of local units seems unrealistic.

In the other hand, one property with the public service's territorial range only in terms of "national/regional/province/local/other" ("other" for rare cases) could be useful. This property combined with the public service's competent authority (a public organization has its address), could be enough to define the spatial scope of the public service and to avoid the use of ATU.

**Comment by barthelemyf** [comment]
Solution implemented: The range of dct:spatial was changed from skos:Concept to dct:Location in version 2.2 for the class cpsv:PublicService.
