### ISSUE TITLE
Cardinality of dct:spatial for class Public Organization is possibly too restrictive

### ISSUE THREAD

**Issue by Maxservais** [SEMICeu/CPSV-AP#30]
As pointed by Ana Rosa Guzmán during the CPSV-AP Webinar of the 10th of April 2019, the cardinality of dct:spatial for the class Public Organisation is possibly too restrictive. The proposed solution is to change the cardinality from [1..1] to [1..*].

**Comment by GabrieleCiasullo** [comment]
I agree with the change of the cardinality proposed.

**Comment by Maxservais** [comment]
This issue will be left open for a few more days. If there are no objections, we will implement the change (cardinality from [1..1] to [1..*] for dct:spatial of Public Organisation) at the end of May 2019.
