### ISSUE TITLE
link public service to UN 2030 Sustainable Development Goals

### ISSUE THREAD

**Issue by pwin** [SEMICeu/CPSV-AP#32]
In addition to classifications of the types of services, it might be helpful to have a way to link the service outcome with the UN 2030 Sustainable Development Goal (2030SDG) - see http://51.15.194.251/Skosmos/un_sdg/en/ for the UN vocabulary

**Comment by NathanGhesq** [comment]
The link  "http://51.15.194.251/Skosmos/un_sdg/en/" is broken, could you please provide the correct reference?

Could this ontology for the SDG be of interest? http://metadata.un.org/sdg/ontology?lang=en

**Comment by NathanGhesq** [comment]
The participants in the webinar on the CPSV-AP review of 06 April 2022 perceived these needs as being out-of-scope regarding CPSV-AP and therefore it will not be added to the model. Anyone objecting to this resolution is invited to reply to this GitHub issue.

Regarding the UN SDG classification, any user of CPSV-AP can make use of the relation isClassifiedBy between the Public Service class and the Concept class to model such classification.
