### ISSUE TITLE
UML class diagram: moving mandatory properties before optionals

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#33]
In the current release (2.2.1) in the UML class diagram, in some classes the optional properties are before the mandatory (Agent, Event, Output, Evidence, Cost). It would be nice to have first mandatory properties folllowed by the optionals

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
