### ISSUE TITLE
UML class diagram: make links to SKOS concepts explict

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#34]
Like in DCAT-AP, where it is shown all the relations towards skos:Concept, it should be done in CPSV-AP where e.g the Public Service class  (and other class too), has properties linking to a skos:Concept (e.g sector, status, type)

**Comment by NathanGhesq** [comment]
In alignment with Core Vocabularies, the addition of the relation towards skos:Concept would clutter the diagram. Therefore, the issue will not be addressed within the next release of CPSV-AP.
