### ISSUE TITLE
Add a relation from Public Service Dataset to Public Service

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#35]
While doing the pilot for Netherlands, there was a need to add a relation from Public Service Dataset to Public Service, in that case dct:hasPart was used.

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
