### ISSUE TITLE
Agent: Alignment with DCAT-AP and CCCEV

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#36]
In DCAT-AP (inherited from DCAT) and CCCEV there is usage of foaf:Agent while in CPSV-AP there is dct:Agent.
In addition in CPOV the class Organization is subclass of org:Organization which is subclass of foaf:Agent

The people from Foaf say that the 2 classes are equivalent:

http://xmlns.com/foaf/spec/#extns_dc

"Dublin Core's notion of Agent is much like FOAF's; Dublin Core says "A resource that acts or has the power to act.", we say "things that do stuff". As nobody has provided a counter-example of something fitting one definition but not the other, we say here that foaf:Agent stands in an 'equivalent class' relationship to dct:Agent (and vice-versa)."

There is one consideration to take in account:
dct:publisher has range dct:Agent

Such relation exists already in DCAT-AP and linked to foaf:Agent

To keep this observation in mind:
https://github.com/w3c/dxwg/issues/111#issuecomment-365531189

**Comment by kareljanr** [comment]
try

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution to the issue was presented, the proposed change will therefore be included in the next release of CPSV-AP.

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
