### ISSUE TITLE
Relation with Core Criterion

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#37]
Currently Public Service class is connected with Criterion Requirement via the hasCriterion relation.

The relation or the definition is a bit misleading:

1) As in Core Criterion and Evidence, there is already a Criterion class, the current relation "hasCriterion" in CPSV-AP would be better changed in "hasCriterionRequirement" (as it points to CriterionRequirement) however in Core Criterion and Evidence there exist already such relation where the domain is cv:RequirementGroup.

Therefore it could be better to point to a RequirementGroup which contains one or more criterions requirements.

2) In the current definition of the relation it is written:

Cardinality [0..n]. Links a Public Service to a class that describes the criteria for needing or using the service, such as residency in a given location, being over a certain age etc. The Criterion class is defined in the Core Criterion and Core Evidence Vocabulary."@en ;

There is a mention to the Criterion class which is not the range of the relation.

**Comment by brechtvdv** [comment]
I believe public services need to point to Criterion instead of CriterionRequirement so CPSV-AP and CCCEV are consistent. If there is the need to have a direct link from a public service to a requirement (for the sake of simplicity), this relation needs to be defined in CCCEV with the domain as reusable as possible

**Comment by kareljanr** [comment]
Based on the comments above I propose that the Public Service class points to Criterion and not Criterion Requirement.

For information:
Definitions
The **Criterion** class represents the rule or principle used to judge, evaluate or assess
something. The Criterion class has the properties described below.

**Criterion requirement** group is the set of requirements that must be fulfilled
together to validate a criterion.

A Criterion can be expressed as a set of requirements where every requirement
must be valid. A **Criterion requirement** is an atomic requirement. This can be better
explained with the examples in section 6.1, where the criterion is "to be eligible to
enter into the cinema to watch a movie", and there are several options to meet this
criterion. One option has two Criterion requirements:
- Holding a ticket
- Being older than eighteen
Some criteria can be expressed with several atomic requirements. A Criterion
requirement can specify the expected value that the Criterion response has to
contain, or a range of threshold values within which the Criterion response has to fit
in.

**Comment by kareljanr** [comment]
Additionally, the CCCEV is being updated, which means that the 'CriterionRequirement' class might disappear. The latest draft version of this update can be seen here:
![cccev](https://user-images.githubusercontent.com/47448176/72244888-8307be00-35ef-11ea-8e55-c67f526ef5e1.png)

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, the 'Criterion Requirement' has been changed to 'Requirement'. The Public Service class points to Requirement via the holdsRequirement relation.
