### ISSUE TITLE
RDF Schema: add ISA Open Metadata license

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#38]
Like for DCAT-AP, the CPSV-AP RDF schema released should include the ISA Open Metadata Licence v1.1

The RDF used in DCAT-AP is:

		<dct:license>
	      <rdf:Description rdf:about="https://joinup.ec.europa.eu/licence/isa-open-metadata-licence-v11">
	        <dct:title>ISA Open Metadata Licence v1.1</dct:title>
	        <cc:attributionName>European Commission</cc:attributionName>
	        <cc:attributionURL rdf:resource="http://ec.europa.eu/"/>
	      </rdf:Description>
	    </dct:license>

To be checked with the best practices document:
http://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html#lic

**Comment by EmidioStani** [comment]
As per issue: https://github.com/SEMICeu/DCAT-AP/issues/63

there must be need to move CC BY 4.0 or CC0 1.0 as per:

https://ec.europa.eu/transparency/regdoc/rep/3/2019/EN/C-2019-1655-F1-EN-MAIN-PART-1.PDF

**Comment by sandervd** [comment]
To me CC0 seems more appropriate (public domain), but there can be arguments both ways.
Anyway moving to creative commons, whether CC BY 4.0 or CC0 will be an improvement.

**Comment by kareljanr** [comment]
There are different ways to license metadata:
[https://www.europeandataportal.eu/sites/default/files/d2.1.2_training_module_2.5_data_and_metadata_licensing_en_edp.pdf](https://www.europeandataportal.eu/sites/default/files/d2.1.2_training_module_2.5_data_and_metadata_licensing_en_edp.pdf)

In particular, the CC BY has been chosen by FOAF ([http://xmlns.com/foaf/spec/](http://xmlns.com/foaf/spec/)), Dublin Core Terms ([https://www.dublincore.org/specifications/dublin-core/dcmi-terms/](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/), see on the bottom) and now DCAT-AP

Therefore we propose to use CC BY 4.0 in alignment of DCAT-AP.

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
