### ISSUE TITLE
Definition of the property hasParticipation is no longer up-to-date

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/CPSV-AP#41]
The definition of the property hasParticipation goes "_The CPSV-AP defines the three basic roles of Competent Authority, Service Provider and Service User but this simple model can be extended if required using the Has Participation property that links to the Participation class._"

Since the properties serviceProvider and serviceUser are deprecated, the definition of hasParticipation should be adjusted accordingly.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
