### ISSUE TITLE
Link to the policy objectives of a service

### ISSUE THREAD

**Issue by pwin** [SEMICeu/CPSV-AP#44]
Many countries (Scotland include) have a national performance framework and also report on the progress made with the United Nations 2030 Sustainable Development Goals.  See http://51.15.194.251/Skosmos/npf/en/  and http://51.15.194.251/Skosmos/un_sdg/en/ for these.

Would colleagues find it helpful to have an extension point in the model that would allow a service to be linked to the policy objectives that it is designed to meet?

**Comment by NathanGhesq** [comment]
The participants in the webinar on the CPSV-AP review of 06 April 2022 perceived these needs as being out-of-scope regarding CPSV-AP and therefore it will not be added to the model. Anyone objecting to this resolution is invited to reply to this GitHub issue.
