### ISSUE TITLE
Definition of the property requires is no longer up to date

### ISSUE THREAD

**Issue by kareljanr** [SEMICeu/CPSV-AP#46]
Description:
The class Input does not exist any more. It has been updated to 'Evidence'.

Definition requires =
One Public Service may require, or in some way make use of, the output of one or
several other Public Services. In this case, for a Public Service to be executed,
another Public Service must be executed beforehand. The nature of the requirement
will be described in the associated Rule or Input.

Proposition:
Change 'Input' with 'Evidence'

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
