### ISSUE TITLE
UML Class diagram: 'type:code[0..n]' indicated mandatory in Criterion Requirement class

### ISSUE THREAD

**Issue by maximepittomvils** [SEMICeu/CPSV-AP#47]
UML Diagram v2.2.1: 

In the UML Diagram in the class Criterion Requirement there is 
type: Code[0..n] which is marked as mandatory, while in the RDF schema, specification and based on the cardinality, it should be optional.

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, the Criterion Requirement class has been replaced with the Requirement class.
