### ISSUE TITLE
Channel

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CPSV-AP#49]
We want to use Channel as a means for secured communication and exchange of information (e.g. documents, questions and clarifications, etc.) between buyers and economic operators.

We have the following questions:

1. Is there a property in the current class Channel used in the CPVS-AP to specify the Data Service end-point URI? We don't see any placeholder for that datum.
2. Is the class Channel is defined in the CPVS-AP namespace, or is it being reused from another ontology/vocabulary? Is reused, which vocabulary, please?

**Comment by EmidioStani** [comment]
Channel is a way to indicate how Public Service is provided, see definition: "A medium through which an Agent provides, uses or interacts in another way with a Public Service. Typical examples include online services, phone, walk-in centres etc."

So the meaning is different thus not suitable for the request.

For point 1) it is better to use DCAT-AP Data Service
2) If you still want to use Channel, its URI is http://data.europa.eu/m8g/Channel taking the CV namespace
