### ISSUE TITLE
Attributes and Annex II of SDG

### ISSUE THREAD

**Issue by OndrejKerka** [SEMICeu/CPSV-AP#50]
Is there any attribute regarding the deadline of 12th December 2020 which is used solely for procedures of Annex II? We would like to know if there is such attribute.

**Comment by NathanGhesq** [comment]
Annex II in the SDGR is not part of CPSV-AP. Life event are already modelled as a subclass of Event and they can be related to zero or more Public Services. Public Services can also produce one or more Output. Could the [SDG model](https://github.com/catalogue-of-services-isa/SDG-search-service-model) satisfy your need with the PolicyCode attribute?

**Comment by EmidioStani** [comment]
This issue can be closed, during the webinar of 07/11/2022 a controlled vocabulary was proposed see:
https://github.com/SEMICeu/Taxonomy#business-and-life-event-taxonomy-file

The discussion could continue on this issue https://github.com/SEMICeu/Taxonomy/issues/3
