### ISSUE TITLE
Filling out of attributes

### ISSUE THREAD

**Issue by OndrejKerka** [SEMICeu/CPSV-AP#51]
How it will work filling out of attributes? Is in CPSV - AP for example some autocomplete? We would like to avoid of duplication.

**Comment by NathanGhesq** [comment]
Could you please provide an example of an attribute to clarify the issue further? In addition, to our understanding, autocompletion is a functionality provided by the application. What does autocompletion mean in this data model?

**Comment by EmidioStani** [comment]
Closing the issue as no further clarification was given
