### ISSUE TITLE
Variants of procedures

### ISSUE THREAD

**Issue by OndrejKerka** [SEMICeu/CPSV-AP#52]
How it is dealt with variants of procedures in the catalogue? In the Czech Republic we have procedures which could be consumed in different situations in different offices. For example for new ID card citizen could apply at municipality or at the Ministry of the Interior, but at the ministry could be applied only for express issue.

**Comment by NathanGhesq** [comment]
We propose to have two public services with two different requirements (using the 'requirement' class) and two competent authorities. They have in common the 'new ID card' which could be a way to classify the public service, or to put them in a catalogue. Can the issue be solved this way?

**Comment by EmidioStani** [comment]
This issue can be closed, an example was given.
