### ISSUE TITLE
Change requests related to Proactive Services

### ISSUE THREAD

**Issue by ioanano** [SEMICeu/CPSV-AP#6]
Following the discussion of proactive services being taken up by governments, the CPSV-AP may need some alterations to accommodate the inclusion of proactive services descriptions in catalogues of services, etc. 
Alternatively, a separate, additional application profile or vocabulary could be created, dedicated specifically to the aspect of proactive services.

**Comment by barthelemyf** [comment]
This is been tackled as part of the work on proactive services, looking at use cases, requirements and how this could be modelled. The working group will be invited to contribute to this work in separate threads.
