### ISSUE TITLE
Legal Resource: Alignment with CCCEV and CPOV

### ISSUE THREAD

**Issue by kareljanr** [SEMICeu/CPSV-AP#61]
CCCEV and CPOV are using the legacy concept 'Formal Framework'.
To align with the current version of CPSV-AP, this should be updated to 'Legal Resource'. Related properties should also be updated.

This issue will be raised with the SEMIC team.

**Comment by anarosa-es** [comment]
CCCEV 2.0 uses [Reference Framework](http://data.europa.eu/m8g/ReferenceFramework) meaning legal and non-legal specifications. For public services provided by Public Administrations the reference framework should be a legal specification.

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, Legal Resource is maintained, and a relation between Rule and Requirement is added.
