### ISSUE TITLE
cv:PublicServiceDataset does not exist, consider change to DCAT-AP dataset

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#62]
CPSV-AP is using cv:PublicServiceDataset to indicate a dataset of public services which is supposed to be a subclass of DCAT-AP dataset.
The class cannot be found in the core vocabularies so better just to reuse DCAT-AP dataset

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by jimjyang** [comment]
@albeaufays 

> This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

When (approx.) is the next release of CPSV-AP planned to come?

**Comment by jimjyang** [comment]
One more question: 

**How to understand and use this `cv:PublicServiceDataset` (which in the next release will be `dcat:Dataset`)**? 

In the PDF, in section 3.2.25, it says "The Is Described At property links a Public Service to the Public Service Dataset(s) (see 3.6) in which it is being described (see section 3.6)", and in section 3.6 it says "The class describes the metadata of where the dataset is being described, for instance on a regional public service portal and/or a national eGovernment portal." 

Does this mean that one uses one or more instances of  `cv:PublicServiceDataset`/`dcat:Dataset` to describe the PublicService itself, in addition to all the properties that are in the Public Service class? Examples of _PublicService-related aspects_ to be described as dataset(s), that are not covered by the properties in the Public Service class? 

On the other hand, what we miss and what we don't think this isDescribedAt property is meant for, is to link to one or more datasets that are needed for the PublicService and to one or more datasets that the PublicService produces (yes, we are aware of the Evidence and Output classes). Let's say that one Evidence is "Certification of incorporation" (a certificate saying that this is a legally registered enterprise, with some "basic" info about the enterprise) and this is a dataset that is already described in the national data portal, so we want to link to that dataset description (from the PublicService or Evidence). How do we do that (what property/ies do we use)?

[Reason I've posted several questions/Issues here recently (more will come :-)), is that we are now working on a Norwegian Application Profile of CPSV-AP, as a specification for our "national catalog of events and public services".]

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, dcat:DataSet is used in alignment with DCAT-AP.
