### ISSUE TITLE
dct:relation has multiple ranges in the rdf schema

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#63]
In CPSV-AP 2.2.1, dct:relation is used 3 times:
1) from event to public service (range: public service)
2) from public service to itself (range: public service)
3) from legal resource to itself (range: legal resource)

As a consequence in the rdf schema, it appears that dct:relation has public service and legal resource as ranges (see: https://github.com/catalogue-of-services-isa/CPSV-AP/blob/master/releases/2.2.1/SC2015DI07446_D02.02_CPSV-AP_v2.2.1_RDF_Schema_v1.00.ttl#L195) .

In OWL when there are multiple ranges it is considered an intersection, independently of the domain of the property, see: https://www.w3.org/TR/owl-ref/#range-def

There can be different options:
1) consider using owl:unionOf
2) consider removal of the dct:relation for legal resource, this could be justified as it is an optional relation and that ELI has already sub-properties of dct:relation (such as "changes", "applied_by"), see: http://publications.europa.eu/resource/cellar/917d16b5-28f6-11e8-b5fe-01aa75ed71a1.0001.01/DOC_1
3) consider creating sub-properties of dct:relation by adding the ranges either towards public service or legal resource 
4) replacing dct:relation with other object properties (less compatible)
5) move such constraints (ranges in general) in the shacl shapes

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to make the relations as subproperties of dct:relation.

**Comment by EmidioStani** [comment]
The relation  Event.relatedService:PublicService is renamed in Event.hasRelatedService:PublicService
The relation PublicService.related:PublicService is renamed in PublicService.relatedService:PublicService

Both have usage note that they are subProperty of dct:relation
