### ISSUE TITLE
Add version info to the ontology

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#64]
Like for DCAT-AP or ELI ontology, it would be nice to add version number associated to the release, such as:

<owl:versionInfo>2.2.1</owl:versionInfo>

Such mechanism would make the release file independent from the naming convention used in the file name.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
