### ISSUE TITLE
How to specify the "address" of a channel?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#66]
How to specify the e-mail address when the channel type is `e-mail`, the homepage/URL when the channel type is `homepage`, etc.? 

The properties that are in the Channel Class do not seem to serve this purpose as far as we understand them. The example in 5.5. doesn't seem to cover this aspect either.

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, the following changes have been made in the Channel class:
- The [Europass](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://data.europa.eu/snb/com-channel/25831c2) controlled vocabulary is recommended in the usage notes of Channel:type
- The property 'description' is added to the Channel class to allow the user to define how to use the channel.

**Comment by jimjyang** [comment]
Sorry that we didn't catch this one when it came up for closing. 

We do not agree.

`dct:description` is for free text description such that the content (e.g., email address, URL, ...) is not machine-readable/-processible (clickable).

**Comment by NathanGhesq** [comment]
Reusers of CPSV-AP can extend the Channel class by adding new properties (email, homepage etc.) or even creating subclasses.

To decide which properties could be added to Channel class, the working group should be involved during a future webinar. 

Additionally, the Channel class should not be confused with the ContactPoint, as the Channel class is the medium through which the Public Services is provided or used.

**Comment by fabian-santi** [comment]
We stumbled on the same issue when trying to implement CPSV. Looking forward to your suggestions.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to:
- Leave the model as is.
- Extend/revise usage notes.
- Investigate vCard usage and add it to the usage note.

**Comment by EmidioStani** [comment]
The usage note of Channel.type was updated
