### ISSUE TITLE
Lack of multilingual support for dct:title and dct:description 

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#67]
Except for the Public Service Dataset Class for which `dct:title` may appear more than once (1..**n**), "The property `dct:title` MUST appear exactly once" (quote from shacl) (1..**1** in the PDF) for the other classes in CPSV-AP. This does not support multilingual titles.  

This comment also applies to `dct:description` for which it is either 0..**1** or 1..**1**.

**Comment by anarosa-es** [comment]
Multilingual support is a must for these two properties, not only for cross-border language but also for countries with several national languages.

**Comment by NathanGhesq** [comment]
This issue was discussed during the webinar of 02/03/2022, where there was consensus to change the cardinality throughout all relevant classes. The change has been made in CPSV-AP 3.0, therefore it will be closed.
