### ISSUE TITLE
[shacl] Use sh:datatype instead of sh:nodeKind for cv:value in cpsv:CostShape-value

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#68]
In the PropertyShape `cpsv:CostShape-value`, `sh:datatype xsd:decimal` (or with another datatype for "nonNegativeDecimal", if any) should be used, instead of `sh:nodeKind sh:IRI`.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
