### ISSUE TITLE
contactPoint: alignment with DCAT-AP?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#69]
To specify a contact point, CPSV-AP uses `cv:hasContactPoint` with range `schema:ContactPoint`, while DCAT-AP uses `dcat:contactPoint` with range `vcard:Kind`. 

Shouldn't CPSV-AP be aligned with DCAT-AP?

**Comment by NathanGhesq** [comment]
In version 3.0, the range of cv:hasContactPoint will be changed to cv:ContactPoint following a decision made in SEMIC core vocabularies. Definitely, alignment should be put in place among Core Vocabularies and DCAT-AP.
