### ISSUE TITLE
Why is schema:hoursAvailable used to express "when the Channel/ContactPoint is _not_ available"? 

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#70]
`schema:hoursAvailable` is now in both the Channel class and the Contact Point class used to express "Availability _restriction_", i.e., "information about when the channel or the contact point is _not_ available". 

From schema.org:
* [schema:hoursAvailable](https://schema.org/hoursAvailable): The hours during which this service or contact is available.
* [schema:specialOpeningHoursSpecification](https://schema.org/specialOpeningHoursSpecification): The special opening hours of a certain place. Use this to explicitly override general opening hours brought in scope by openingHoursSpecification or openingHours.

Shouldn't `schema:specialOpeningHoursSpecification` (instead of`schema:hoursAvailable`) be used for "Availability restriction"?

**Comment by NathanGhesq** [comment]
In version 3.0, schema.hourAvailable is replaced by the Core Vocabulary namespace. For this property, we can propose the equivalent of schema:specialOpeningHoursSpecification.
