### ISSUE TITLE
channels owned by non public organizations and costs defined by non public organizations

### ISSUE THREAD

**Issue by wouterdc** [SEMICeu/CPSV-AP#71]
According to the CPSV-AP model a channel of a public service is always owned by a public organization. In reality a channel for public services can also be owned by non public organisation (eg. in case that a competent authority delegates the distribution of a service).
For example: Parking cards for city residents (= public service) should be requested at a website of a private parking company in some cities in Flanders because the city government has appointed the private parking company to provide this service.
Because of that, in my opinion, the relation 'isOwnedBy' should be between 'Channel' and 'Agent' instead of between 'Channel' and 'Public organization'

Secondly, in those cases, the private organizations can also define their own administrative cost. For that reason, I also believe that the relation 'isDefinedBy' should be between 'Cost' and 'Agent' instead of 'Cost' and 'Public organzation'

**Comment by wouterdc** [comment]
@barthelemyf fyi

**Comment by anarosa-es** [comment]
We need to have a clear definition of public service, its scope, its common parts and only then we can discuss how private organisations can be involved.

**Comment by EmidioStani** [comment]
This issue was discussed during the webinar of 02/03/2022, where there was consensus to change the range of ownedBy and definedBy to Org:Organization The change has been made in CPSV-AP 3.0, therefore it will be closed.
