### ISSUE TITLE
(editorial) Annex V - Registering a branch

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#74]
In Annex V, the description "This business event groups public services relating to the start-up of a new activity, and that have to be done before you can start with the particular activity." for "Registering a branch" under both "Starting business" and "Doing business" is for "Starting a new activity", and should be replaced by the description of "Registering a branch" under "Starting cross-border business" which is "This business event groups public services for opening affiliates and representative offices."

**Comment by NathanGhesq** [comment]
Thank you for reporting this. The PDF documentation of CPSV-AP 2.2.1 will not be updated as we will continue to release CPSV-AP in HTML. 

We encourage Member States to use the classification from the [SDGR](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2018.295.01.0001.01.ENG&toc=OJ:L:2018:295:TOC) which includes the event of starting, running and closing a business.

**Comment by jimjyang** [comment]
@NathanGhesq 

Very good indeed that CPSV-AP v.3 refers to SDGR instead of duplicating the classifications. 

A follow-up question: Will the classifications in SDGR be published by (e.g.) the Publications Office as machine-readable resources, and when?

**Comment by EmidioStani** [comment]
This issue can be closed, during the webinar of 07/11/2022 it was presented a classification, see: https://github.com/SEMICeu/Taxonomy#business-and-life-event-taxonomy-file

The discussion could continue on this issue https://github.com/SEMICeu/Taxonomy/issues/3
