### ISSUE TITLE
Add optional dct:language to the Output class

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#77]
Especially for cross-border provision of public services, it is important to describe in which language(s) an Output (e.g. a birth certificate) from a Public Service may be. 

We propose therefore to add dct:language to the Output class (optional, 0..n, range dct:LinguisticSystem, and also with the requirement that the [Authority Table | language](https://op.europa.eu/s/vMEq) must be used).

**Comment by NathanGhesq** [comment]
This property has been added in CPSV-AP 3.0, therefore this issue will be closed.
