### ISSUE TITLE
Need of 1-to-many relationship between Public Service and Public Organization

### ISSUE THREAD

**Issue by LorenzoIan** [SEMICeu/CPSV-AP#78]
Public Service - Public Organization relationship: the model has 1-to-1 relationship and it does not allow to map the cases in which the same service is offered by more competent authorities.

e.g. university enrollment
-	Public Service: university enrollment
-	Public Organization (competent authority): more than one university provide this service in the same location

Proposal: the relationship between Public Service and Public Organisation should be 1-to-many

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, the cardinality of hasCompetentAuthority has been extended to [1..n]. Therefore, this issue will be closed.
