### ISSUE TITLE
Addressee and SDG Annexes

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/CPSV-AP#79]
SDG categories, derived from SDG Annexes and used by the SDG link repository, are classified under two top groups, "BUSINESS" or "CITIZEN". A procedure linked to the SDG can be classified under one or more categories.

Since it is possible to have procedures aimed to organisations that are not a business, like non-profit organisations, it is recommended to rename the two top groups as LEGAL PERSON / NATURAL PERSON. In this way, we have both the addressee(s) and thematic classification or a public service represented by one property.

On the other hand, since SDG categories only cover the SDG procedures, this property cannot be mandatory if we do not include an "OTHER" option to each of the two top groups and each of the main areas. Making mandatory this property can guarantee that the addressee and the SDG classification of any public service are always considered. Thus, when LEGAL PERSON/OTHER, NATURAL PERSON/OTHER or both are used, this property will tell that the public service is not a SDG procedure and who is(are) the addressee(s).

However, we should learn from the issues that this classification has posed to the SDG portal (Your Europe) and adopt remedial measures. In particular there are issues from the redundancy of topics in the two annexes and the granularity of the categories to used to classify the procedure.

**Comment by NathanGhesq** [comment]
This issue requires investigation from the editorial team to better define the addressee. For example, describing it as a codelist, or as a foaf:group for which classes like Channel can depend upon.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to:
- Add property "addressee" (code) to Public Service to indicate the addressee of a Public Service.
- Review using Dublin Core Audience as a recommendation.
- Explain how to expand on a code list (overall working point: Core Vocabularies).

**Comment by EmidioStani** [comment]
This issue is in part solved by #96

**Comment by EmidioStani** [comment]
A new issue is opened on the style guide https://github.com/SEMICeu/style-guide/issues/89, the discussion about code list can continue over there.
