### ISSUE TITLE
ELI Alignment

### ISSUE THREAD

**Issue by ioanano** [SEMICeu/CPSV-AP#8]
Differences:
- “Formal framework” in CPSV-AP vs. “legal resource” in ELI
- “Status” in CPSV-AP vs. “in_force” in ELI - the possible values are also slightly different (“in force”, “partially in force”, “not in force”)
- “Related” in CPSV-AP and “related_to” in ELI are not equivalent: in ELI it “indicates a somehow related other document”, while in CPSV-AP it “represents another instance of the Formal Framework class that is related to the particular Formal Framework being described”
- “Type” is optional in CPSV-AP, while “type_document” is mandatory in ELI

**Comment by barthelemyf** [comment]
Formal Framework was replaced by Legal Resource in alignment with [ELI](https://publications.europa.eu/en/web/eu-vocabularies/eli). All other properties were removed, indicating to CPSV-AP users to refer to ELI. 
The remaining property in CSPV-AP is “related” (dct:relation) which is different from “relatedTo” in ELI. How should CPSV-AP model this?
Both properties are currently set as optional. We would propose to align to he definition of ELI for “relatedTo” in the next version of the CPSV-AP.

The current definition in CPSV-AP 2.2 is: “This property represents another instance of the Legal Resource class that is related to the particular Legal Resource being described.” 
While the definition of “relatedTo” in ELI states: “Indicates a somehow related other document, not necessarily a legal resource. Note that citation links should use the cites property.”
