### ISSUE TITLE
Concession Contract

### ISSUE THREAD

**Issue by NathanGhesq** [SEMICeu/CPSV-AP#80]
With the objective of delegating the public service to a private organisation, the class Concession Contract ([definition](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0023&from=EN), art 11. This definition is similar to the definition on [DBPedia](https://dbpedia.org/page/Concession_%28contract%29#)) has been proposed in the webinar of 06/04/2022, with the following properties:
- description
- identifier
- name

and the following relations:
- It is a subclass of ePO:contract
- Relation towards LegalResource (e.g. 'established in’) or relation from LegalResource to concession
- Relation towards Public Organisation (defined[ by: hasContractingAuthority, Art.11.](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0023&from=EN))
- Relation towards an organization (defined[ by: hasEconomicOperator](https://spec.edmcouncil.org/fibo/ontology/FND/Agreements/Contracts/Contract))

This would help to model cases like Issue #71 or concessions for private highways. However, the proposition does not intend to cover licences to develop an activity that can be considered a public service, such as telecom services, health services or educational services.

If there are no objections, this will be added in CPSV-AP 3.0.

**Comment by EmidioStani** [comment]
The class has been included in CPSV-AP 3.0.0
