### ISSUE TITLE
range for dct:identifier shouldn't be rdf:langString 

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#82]
Good to see that `rdf:langString` is now used as the range for the properties which should have language tagged text (e.g., `dct:title`, `dct:description` etc.). 

However, `dct:identifier` isn't language specific/dependent and thus the range shouldn't be `rdf:langString`, but `rdfs:Literal`.

**Comment by NathanGhesq** [comment]
We agree that dct:identifier should be rdfs:Literal. This change will be included in CPSV-AP 3.0.0.
