### ISSUE TITLE
range for dct:spatial should be Code (skos:Concept)

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#83]
In the class Public Organization, the range for the property spatial (`dct:spatial`) should be Code (skos:Concept) (and not [AdministrativeTerritorialUnit](http://data.europa.eu/88u/dataset/atu-type) which is a controlled vocabulary), as for the other similar properties (e.g. `dct:type`). 

Or, `dct:Location` as the range for `dct:spatial`?

**Comment by NathanGhesq** [comment]
The range of dct:spatial has been changed from dct:location to the AdministrativeTerritorialUnit class to be consistent with Core Public Organisation Vocabulary (CPOV), as Public Organisation is defined in CPOV. 

This issue is brought to CPOV.
