### ISSUE TITLE
UML-diagram in the HTML-version of CSPV-AP v.3.00 is not updated (?)

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#85]
The UML-diagram (jpg) shown under Overview in the HTML-version of CPSV-AP v.3.0.0 seems out of sync with the rest of the content, right?

I mean this one: https://catalogue-of-services-isa.github.io/CPSV-AP/releases/3.0.0/html/overview.jpg

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

what kind of differences you see ? The diagram should be in sync, so if you spot difference please let us know and if we fix it.

**Comment by jimjyang** [comment]
> Hello @jimjyang ,
> 
> what kind of differences you see ? The diagram should be in sync, so if you spot difference please let us know and if we fix it.

e.g., in the text I couldn't find the property "implements" in the class cpsv:Rule, which is in the diagram from (cpsv:Rule to eli:LegalResource).

**Comment by jimjyang** [comment]
... and, if `cpsv:implements` was meant to be removed, why?

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

thanks for reporting this; the cpsv:implements was not removed, it was a misconfiguration in the UML class diagram,
