### ISSUE TITLE
Missing possibility for specifying normal opening hours as structured data in Channel and Contact point

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#86]
This comment applies to both the class [Channel](http://data.europa.eu/m8g/Channel) and the class [Contact Point](http://data.europa.eu/m8g/ContactPoint), with Channel as an example here.

With v.3.00 it is now possible to specify: 
* [opening hours](http://data.europa.eu/m8g/openingHours) as Text (rdf:langString) for the normal opening hours, and
* [availability restriction](http://data.europa.eu/m8g/specialOpeningHoursSpecification) as structured data (cv:OpeningHoursSpecification) for opening hours restriction, 

but not normal opening hours as structured data. 

In general, we should promote and thus make it possible to use as much as possible structured data. In order to increase cross-border semantic interoperability CPSV-AP should specify how to do this, instead of extensions at the national level. 

We propose therefore to add explicitly to the class Channel and Contact point the following property: 
* normal opening hours specification (cv:normalOpenHoursSpecification), 0..1, with cv:OpeningHoursSpecification as range.

**Comment by NathanGhesq** [comment]
This is a problem that could be solved within SEMIC to agree on a strategy on how OpeningHours as a general concept should be dealt with.

We can keep this issue open for future releases of CPSV-AP, in alignment with other Core Vocabularies to be discussed with the working group.

**Comment by EmidioStani** [comment]
This issue depends partially on the outcome of the webinar on Core Public Organisation, the proposition is make Channel behaving like Contact Point towards TemporalEntity

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to add same relations (openingHours and availabilityRestriction) to Channel like for ContactPoint towards TemporalEntity.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
