### ISSUE TITLE
Contact page too narrowly defined

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#87]
The property [contact page](http://data.europa.eu/m8g/contactPage) in the class Contact point is now too narrowly described/defined as "A contact form that could be used to reach out the contact point". A contact page could also by a chat/chatbot, i.e., not only a contact form. 

We propose therefore to change the description to for instance "A contact page that ...", alternatively with "contact form" mentioned as example.

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

we agree with the proposal, also because the name of the property is itself "contact page"
