### ISSUE TITLE
Evidence as subclass of Dataset

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#89]
In [CCCEV v.2.00](https://semiceu.github.io/CCCEV/releases/2.00/#Evidence) which we understand CPSV-AP v.3.0.0 (re)uses, the class Evidence is a subclass of Dataset. 

Any reason why [CPSP-AP v.3.0.0](https://catalogue-of-services-isa.github.io/CPSV-AP/releases/3.0.0/#Event) doesn't explicitly mention that Evidence is a subclass of Dataset?

**Comment by EmidioStani** [comment]
Hello @jimjyang , there was no particular reason, as you requested we added and also because it connect existing components in the diagram without making it cluttered
