### ISSUE TITLE
Public Service - Type - authoritative source of the codelist COFOG is not accessible for now

### ISSUE THREAD

**Issue by barthelemyf** [SEMICeu/CPSV-AP#9]
It was identified that the authoritative source of the codelist COFOG referred to in the CPSV-AP specification v2.1 for dct:type of Public Service was no longer publicly available: [link](http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=4).

How should the CPSV-AP model deal with this issue?

This issue is related to [https://github.com/catalogue-of-services-isa/cos-testing/issues/2](https://github.com/catalogue-of-services-isa/cos-testing/issues/2) and [https://github.com/catalogue-of-services-isa/cpsv-ap_creator/issues/3](https://github.com/catalogue-of-services-isa/cpsv-ap_creator/issues/3)

**Comment by pwin** [comment]
I am in discussion with Luis Gonzales Morales in UN about this, and hope to have a resolution with UN hosting this and other vocabularies (including those relating to SDG)

**Comment by anarosa-es** [comment]
The problem I see on using COFOG for the "type" public service attribute is that this taxonomy is only related to functions of expenditure and I'm afraid that CoS can include public services without expenditures.

**Comment by anarosa-es** [comment]
The problem I see on using COFOG for the "type" public service attribute is that this taxonomy is only related to functions of expenditure and I'm afraid that CoS can include public services without expenditures, like "getting a birth certificate". 

However, this could be useful if CoS also registers the mapping between a public service and the national account system.

**Comment by pwin** [comment]
Perhaps we need a set of potential vocabularies that we can use here rather
than trying to have only one consolidated vocabulary ... It could be an
extension point

**Comment by Maxservais** [comment]
During the webinar of the 10th of April 2019, it was explained that the authoritative source of the codelist COFOG referred to in the CPSV-AP specification v2.1 for dct:type of Public Service was no longer publicly available. As a result, it has been agreed that, for the time being, the issue would be left open on GitHub until the UN Nations address the issue but COFOG would be removed from the specifications of the CPSV-AP.

**Comment by guascce** [comment]
In the EU Vocabularies there is an Authority table https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/main-activity?target=About that uses the first level of the COFOG.
Could we ask Publication Office to maintain a full replica of the COFOG?

**Comment by EmidioStani** [comment]
The original link (at the top of the discussion) on COFOG works, it points a PDF though.

However, during the last webinar it was approved that the Authority Table of Publications Office would be recommended
