### ISSUE TITLE
Inconsistency between HTML- and RDF-representation of CPSV-AP v.3.0.0

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#90]
https://github.com/catalogue-of-services-isa/CPSV-AP/blob/0d94806d021913d69e4c16efa2a08f012e616571/releases/3.0.0/rdf/cpsv-ap.ttl#L250 says `0..1` while [HTML-version](https://catalogue-of-services-isa.github.io/CPSV-AP/releases/3.0.0/#Public%20Service%3Athematic%20area) says `0..*`.

**Comment by EmidioStani** [comment]
Thanks @jimjyang  for reporting this, indeed the Thematic Area has cardinality 0..* so the RDF is wrong, this has been fixed.
