### ISSUE TITLE
Missing properties cccev:expectedDataType, cccev:expectedValue, cccev:maximumValue, cccev:minimumValue

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#93]
Should I post this issue to CCCEV (as well)? 

CPSV-AP v.3.0.0 uses [CCCEV v.2.00](https://semiceu.github.io/CCCEV/releases/2.00/). 

[The class CriterionRequirement in CCCEV v.1](https://github.com/SEMICeu/CCCEV/blob/master/releases/1.00/core_evidence_and_core_criterion_vocabulary_version_1.0.0.png) had properties expectedDataType, expectedValue, maximumValue, minimumValue etc., which are necessary to specify e.g. the requirement "age (positiveInteger) >= 20" machin-readably. 

The class Criterion Requirement in CCCEV v.1 is split into the classes Requirement, Information Requirement and Constraint in [CCCEV v.2](https://github.com/catalogue-of-services-isa/CPSV-AP/blob/master/releases/3.0.0/html/overview.jpg), without explicitly mentioning where the abovementioned (and several other) properties of Criterion Requirement are in v.2.  

Our questions are: 
1. Where are the properties of Criterion Requirement in CCCEV v.1 now in CCCEV v.2? If they are intentionally omitted, why? As exemplified above, they are necessary in order to have machin-readable specifications of requirements and they should be standardized at the EU level. 
2. If they are not going to be included in CCCEV v.2, are the properties cccev:expectedDataType (with cccev namespace) etc. deprecated, or is it still allowed and advisable to use them (with new domains), in our national application profiles of CPSV-AP?

**Comment by EmidioStani** [comment]
Hello @jimjyang,

CriterionRequirement is indeed deprecated in CCCEV 2.0 to which CPSV-AP is aligned to. I believe this issue should be in CCCEV.

**Comment by jimjyang** [comment]
I've posted this to CCCEV now, https://github.com/SEMICeu/CCCEV/issues/45

**Comment by EmidioStani** [comment]
Closing this, it will follow on CCCEV
