### ISSUE TITLE
Use of cccev:EvidenceType instead of cv:Evidence

### ISSUE THREAD

**Issue by zeginis** [SEMICeu/CPSV-AP#95]
The updated version of CPSV-AP uses the `cv:Evidence` (from the CCCEV vocabulary) class to define the input of a` cpsv:PublicService`

According to CCCEV:

- The `cccev:Evidence` is bound to a specific agent (e.g. the ID card of John Doe)
- The `cccev:EvidenceType` provides Information about the characteristics of an Evidence (e.g. the ID card in general)

These definitions are explainded here by an example: https://github.com/SEMICeu/CCCEV/blob/master/releases/2.00/CCCEV_AnExplanatoryExample.pdf

**So I think that the input of a cpsv:PublicService should be linked with the `cccev:EvidenceType` insted of the cv:Evidence**. The input should define the valid types of input (e.g. ID card) and not the specific instances (e.g. ID card of John Doe). In my understanding the role of CPSV-AP is to provide information about public services and not specific information of a public service execution

This addition will also require the use of the intermediate class `cccev:EvidenceTypeList`  to  link the `cv:Requirement` with the `cccev:EvidenceType` as indicated in CCCEV

This is an update we have already proposed at a published journal article https://www.mdpi.com/1608048
![CPSV_AP_extension_large_letters](https://user-images.githubusercontent.com/3403887/171150146-a6a23580-c06e-4ae7-81cb-6e99906c23ac.jpeg)

**Comment by EmidioStani** [comment]
Hello @zeginis, thanks for your input,

the way CSPV-AP is designed, it allows indeed flexibility in choosing whether to describe a public service or use it for execution.
In the first case one can create its own catalogue, as a website listing the public services or simply creating an instance of public service. 

In the link associated: https://github.com/SEMICeu/CCCEV/blob/master/releases/2.00/CCCEV_AnExplanatoryExample.pdf
os slide 11, John Doe provides his ID card as Evidence while the EvidenceType (any id card) is declared by the Information Requirement (subclass of Requirement).

As Evidence is connected to EvidenceType via "isConformantTo" relation, one can find EvidenceType by following such relation.

**Comment by zeginis** [comment]
Thank you @EmidioStani  for your answer.

So in the case I need to create a catalogue listing public services, how to describe that the public service requires and ID card (any id card) as input?

The Evidence class of CCCEV is boud to specific Agents so we need to use ONLY EvidenceType.
In the case you describe one can find the EvidenceType through the "isConformantTo" link with the Evidence.
However, in my understanding, the Evidence class (as defined by CCCEV) is not applicable when providing descriptions of public services to be added in a catalogue

**Comment by EmidioStani** [comment]
Hello @zeginis ,

so far the way would be via the Requirement and EvidenceTypeList classes to EvidenceType, which make sense, even though I see it is longer chain.

**Comment by zeginis** [comment]
Hello @EmidioStani,

Yes in deed this path you are proposing makes sense and is compliant with CCCEV.
You could also consider adding a direct link between "Public Service" and EvidenceType to be used for Public Service descriptions. 
The use of the same model to describe a public service or use it for execution requires two types of "input" for the Public Service. 
- For the case of Public Service descriptions it needs to describe the generic type e.g. any id card (EvicenceType)
- Fro the case of Public Service execution it needs to describe the instances e.g ID card of John Doe (Evidence)

**Comment by EmidioStani** [comment]
Hello @zeginis ,

we could propose this for the next CPSV-AP release. This issue will be kept open until decision has been made.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to add relation "hasInputType" between PublicService and EvidenceType to support public service descriptions case.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
