### ISSUE TITLE
Public Organization - preferred label: should be 1..* 

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#99]
[The property preferred label in the class Public Organization](https://semiceu.github.io/CPSV-AP/releases/3.0.0/#Public%20Organization%3Apreferred%20label) is now 1..1. It should be 1..*, to allow different preferred names in different languages, e.g. "European Commission" in all the European languages.

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

indeed, likewise other classes with multiple cardinalities for title and description, the cardinality for preferred label could be relaxed, to be considered for next minor release.

This issue should be kept open until it is fixed.

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to:
- Relax cardinality like other classes with name/title and description.
- Provide a clarification in usage note that the skos:prefLabel restriction applies here as well.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
